micronaut:
  application:
    name: web_server
  server:
    cors:
        enabled: true
        configurations:
          web:
            allowedOrigins:
              - http://localhost:3000
              - ^192\.168\.1\.[0-9]+:3000$