micronaut:
  application:
    name: web_server
  server:
    cors:
        enabled: true
dataSource:
  #Uncomment for persistent db
  url: jdbc:h2:mem:devDb
  #url: jdbc:h2:file:d:\files\minecraft\minecraft_web_server\devDB;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  pooled: true
  jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
